# Generated by Django 5.2 on 2025-04-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberingRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='ABC / DEF')),
                ('start', models.BigIntegerField(verbose_name='От')),
                ('end', models.BigIntegerField(verbose_name='До')),
                ('capacity', models.IntegerField(verbose_name='Ёмкость')),
                ('operator', models.CharField(max_length=255, verbose_name='Оператор')),
                ('region', models.CharField(max_length=500, verbose_name='Регион')),
                ('territory', models.TextField(blank=True, verbose_name='Территория ГАР')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Реестр российской системы и плана нумерации',
                'verbose_name_plural': 'Реестр российской системы и плана нумерации',
            },
        ),
    ]
